### ISSUE TITLE
Making code more pythonic

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/vfatqc-python-scripts#302] opened 2020-03-06 17:22 UTC
## Brief summary of issue

A lot of scripts are invoked by aggreators like `run_scans.py` through `subprocess.call`
This is in general anti-pythonic way of working with python code and also provides some problems for development, in particular `subprocess.call` doesn't preserve the `env` variables unless specifically asked for. As a consequence, testing/debugging in a virtual environment is much complicated. There could be two solutions:
1. Make normal pythonic calls like 
```python
from my_module import my_scan
my_scan(args)
```
which requires a bit of changes in the scanning tools
2. Force env passing in `subprocess.call`
see  e.g. https://stackoverflow.com/questions/16430609/virtualenv-and-subprocess-call-in-mixed-python-2-7-3-3-environment

I would vote for the first option, but not sure whether we want to pursue it for the legacy release...
### Types of issue

- [ ] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)
- [x] Code refactoring

**Comment by lpetre-ulb** [comment] 2020-03-08 10:55
> [...] in particular subprocess.call doesn't preserve the env variables unless specifically asked for. As a consequence, testing/debugging in a virtual environment is much complicated.

> 2. Force env passing in `subprocess.call`
> see e.g. https://stackoverflow.com/questions/16430609/virtualenv-and-subprocess-call-in-mixed-python-2-7-3-3-environment

Are you sure than the environment is not preserved? The documentation [says the opposite](https://docs.python.org/2/library/subprocess.html#popen-constructor). Moreover, I cannot reproduce the issue in a minimal working example:
``` bash
$ python
>>> import subprocess
>>> subprocess.call('env')
[...]
LD_LIBRARY_PATH=/home/lpetre/GEM/cmsgemos/gempython/lib/linux/x86_64_centos7:/home/lpetre/GEM/cmsgemos/gemhardware/lib/linux/x86_64_centos7:/home/lpetre/GEM/cmsgemos/gemutils/lib/linux/x86_64_centos7:/home/lpetre/GEM/xhal/xhalcore/lib:/home/lpetre/GEM/reg_utils/rwreg/x86_64/lib:/opt/xdaq/lib:/opt/wiscrpcsvc/lib:/opt/cactus/lib:
[...]
PATH=/opt/Xilinx/SDK/2016.2/bin:/opt/Xilinx/SDK/2016.2/gnu/microblaze/lin/bin:/opt/Xilinx/SDK/2016.2/gnu/arm/lin/bin:/opt/Xilinx/SDK/2016.2/gnu/microblaze/linux_toolchain/lin64_be/bin:/opt/Xilinx/SDK/2016.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/opt/Xilinx/SDK/2016.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/opt/Xilinx/SDK/2016.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/opt/Xilinx/SDK/2016.2/gnu/aarch64/lin/aarch64-linux/bin:/opt/Xilinx/SDK/2016.2/gnu/aarch64/lin/aarch64-none/bin:/opt/Xilinx/SDK/2016.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/opt/Xilinx/SDK/2016.2/tps/lnx64/cmake-3.3.2/bin:/home/lpetre/GEM/pyvenv/lib/python2.7/site-packages/gempython/scripts:/home/lpetre/GEM/xhal/python/reg_interface_gem/scripts:/home/lpetre/GEM/reg_utils/python/reg_interface/scripts:/home/lpetre/GEM/pyvenv/bin:/home/lpetre/scripts:/usr/sue/bin:/opt/xdaq/sbin:/opt/xdaq/bin:/usr/lib64/qt-3.3/bin:/home/lpetre/perl5/bin:/opt/cactus/bin/amc13:/opt/cactus/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/lpetre/.local/bin:/home/lpetre/bin
[...]
```

Maybe you missed an environment variable/path?

> I would vote for the first option, but not sure whether we want to pursue it for the legacy release...

The first option (pythonic calls) would be ideal, but I wouldn't pursue it in the legacy branches. The changes are likely to be time consuming and could introduce (many) bugs. Also, do we want to support virtual environments in the legacy release or support only RPM installation?

**Comment by AndrewLevin** [comment] 2020-03-08 11:20
I don't understand this sentence "Also, do we want to support virtual environments in the legacy release or support only RPM installation?" Typically, we install the RPM inside of the virtual environment. If we don't support virtual environments, how can we test the rpm?

**Comment by lpetre-ulb** [comment] 2020-03-08 11:32
We do not install the RPM inside the virtual environment (at least, I never have), but the Python packages, or code, directly. By "support", I mean thorough documentation that everyone should be able to follow, even in remote test stands. AFAIK, the current local installation system, with all it quirks, works and is only going to be used by an handful of developers.

**Comment by AndrewLevin** [comment] 2020-03-08 12:16
sorry, you are right, when I do `pip install  -U vfatqc-python-scripts/rpm/gempython_vfatqc-2.4.3.tar.gz  --no-deps` it is different from installing an rpm

**Comment by lpetre-ulb** [comment] 2020-05-18 16:39
As agreed in the conversation, more "Pythonic" code would be ideal. Since it works well enough for QC, the issue is not worth being fixed in the legacy software.

**Closed as completed by lpetre-ulb** 2020-05-18 16:39 UTC
Labels: Type: Question, Status: Wontfix
