### ISSUE TITLE
Add TU Mask option to "confChamber.py"

### ISSUE THREAD

**Issue by bregnery** [cms-gem-daq-project/vfatqc-python-scripts#299] opened 2020-02-11 09:00 UTC
## Brief summary of feature request
At point 5, we have several chambers with vfats that will need TU Masks to mask bad sbits. This can be done in `gem_reg.py`, but during operations this process will be quite tedious. It would useful to have an option for this in `confChamber.py` so that chambers can be easily configured for p5 operations.

### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Expected Behavior

Ideally, `confChamber.py` would have a new option "SBitMask" where the user can provide a vfat number and a TU Mask to mask the affected vfat

```
confChamber.py --SBitMask  (vfat=13,  TUmask=0x20)
```

## Current Behavior

Currently, the only way to apply these masks is via `gem_reg.py`

## Possible Solution (for bugs)

Here is an example TU Mask register name `GEM_AMC.OH.OH2.FPGA.TRIG.CTRL.TU_MASK.VFAT13_TU_MASK`

## Context (for feature requests)

Having to manaully apply these masks in `gem_reg.py` is tedious and easily overlooked. For p5 operations, it is best if this option is included so that the GEM shifter can be handed a simple set of commands with TU masks already included.

**Comment by lpetre-ulb** [comment] 2020-03-01 16:35
This information will be included in the GEM configuration database and applied to the hardware during the "Configuring" step.

The issue is probably a "Won't fix" in `vfatqc-python-scripts`.

**Closed as completed** 2020-03-05 17:56 UTC
Labels: Status: Wontfix
